import { CTA, FeatureCard, ImagePanel, Metric, PageHero, SectionTitle } from "@/components/ui";

export default function InfrastructurePage() {
  return <>
    <PageHero eyebrow="Capacity engineered for reliability" title="World-Class Manufacturing Infrastructure" text="Purpose-built processing, cold storage and dispatch systems supporting high-volume food ingredient programs." image="/images/infrastructure-1.png" />
    <section className="metrics-band"><div className="container metric-row"><Metric value="18,000" label="MT annual capacity" /><Metric value="65,000" label="sq. ft. production" /><Metric value="4" label="dedicated processing lines" /><Metric value="24/7" label="utilities monitoring" /></div></section>
    <section className="section container facility-grid"><div><SectionTitle eyebrow="Processing unit" title="Clean-flow production architecture" text="Separated material and personnel movement, hygienic zoning and stainless-contact systems reduce contamination risk while improving line efficiency." /><div className="feature-grid two"><FeatureCard icon="factory" title="Automated processing" text="Integrated conveying, drying and packing systems for repeatable output." /><FeatureCard icon="shield" title="Hygienic zoning" text="Controlled access, sanitation gates and environmental monitoring." /></div></div><ImagePanel src="/images/infrastructure-2.png" alt="Automated food processing machinery" /></section>
    <section className="section storage"><div className="container story-grid"><ImagePanel src="/images/infrastructure-3.png" alt="Industrial cold storage facility" /><div><SectionTitle eyebrow="Storage & preservation" title="Multi-zone cold storage" text="Temperature-managed zones protect raw crops, frozen products and finished ingredients under the conditions each category requires." /><div className="temperature-card"><strong>-22°C to +18°C</strong><span>Multi-zone operating range</span></div><div className="check-list"><span>Real-time temperature alarms</span><span>FIFO inventory controls</span><span>Dock-to-storage traceability</span></div></div></div></section>
    <section className="section container facility-grid reverse"><div><SectionTitle eyebrow="Logistics & supply chain" title="Designed for efficient dispatch" text="Covered loading bays, container staging and export documentation workflows keep shipments protected and moving." /><div className="feature-grid two"><FeatureCard icon="box" title="Export packing" text="Barrier liners, palletization and container loading options." /><FeatureCard icon="globe" title="Port connectivity" text="Efficient access to Mundra and Nhava Sheva trade routes." /></div></div><ImagePanel src="/images/infrastructure-4.png" alt="Modern industrial manufacturing campus" /></section>
    <section className="section sustainability"><div className="container"><SectionTitle center eyebrow="Responsible scale" title="Engineering a greener industrial future" /><div className="feature-grid"><FeatureCard icon="leaf" title="Heat recovery" text="Recovered thermal energy improves dryer and utility efficiency." /><FeatureCard icon="leaf" title="Water stewardship" text="Cleaning systems are designed to reduce and reuse process water." /><FeatureCard icon="leaf" title="Crop utilization" text="By-products are directed toward productive secondary uses." /></div></div></section>
    <CTA title="Scale your supply chain with reliable infrastructure" text="Talk to our team about reserved capacity, contract production and multi-year ingredient programs." />
  </>;
}
