import { ContactForm } from "@/components/contact-form";
import { Icon } from "@/components/icon";
import { OpenMap } from "@/components/open-map";
import { ImagePanel, PageHero, SectionTitle } from "@/components/ui";

export default function ContactPage() { return <>
  <PageHero compact eyebrow="Enterprise solutions" title="Partner with De'Hydra Foods" text="From bulk procurement to custom ingredient programs, our team is ready to support your global supply chain." image="/images/contact-1.png"/>
  <section className="section container contact-layout"><div><SectionTitle eyebrow="B2B inquiry portal" title="Tell us what your production line needs" text="Share your commercial and technical requirements for volume pricing, samples and specification support."/><ContactForm/></div><aside className="contact-aside"><div className="contact-card"><h3>Direct channels</h3><span><Icon name="pin"/><b>Global HQ</b> Dubai, UAE</span><span><Icon name="phone"/><b>Enterprise sales</b> +971 4 456 7890</span><span><Icon name="mail"/><b>Email</b> sales@dehydrafoods.com</span></div><div className="contact-card teal"><h3>Manufacturing hub</h3><p>Mahuva Industrial Estate<br/>Gujarat, India</p><a href="mailto:export@dehydrafoods.com">export@dehydrafoods.com</a><a href="tel:+912844222333">+91 2844 222 333</a></div><div className="contact-card"><h3>Response target</h3><strong className="big-number">1 business day</strong><p>For complete industrial inquiries with company details.</p></div></aside></section>
  <section className="section footprint"><div className="container story-grid"><div><SectionTitle eyebrow="Our global footprint" title="Commercial reach. Manufacturing control." text="A Dubai commercial hub and Gujarat production base connect customer requirements directly to manufacturing and export execution."/><div className="location-pills"><span>Global HQ · Dubai</span><span>Production · Gujarat</span><span>Supply · 40+ countries</span></div></div><OpenMap className="map-card"/></div></section>
  <section className="section container audit-banner"><ImagePanel src="/images/contact-3.png" alt="Pristine food manufacturing facility"/><div><SectionTitle eyebrow="Technical due diligence" title="Schedule a facility audit" text="We welcome qualified corporate partners to verify our hygiene, quality and production systems first-hand."/><a className="button primary" href="mailto:sales@dehydrafoods.com?subject=Facility%20audit%20request">Request an audit</a></div></section>
  </>; }
