import Link from "next/link";
import { Icon } from "@/components/icon";
import { CTA, ImagePanel, PageHero, SectionTitle } from "@/components/ui";

const specs = [["Moisture", "Max 7.0%"], ["Bulk density", "280–380 g/L"], ["Mesh size", "2–10 mm"], ["Additives", "Mono & diglycerides"], ["Rehydration ratio", "1:5 approx."], ["Shelf life", "12 months"]];

export default function PotatoPage() { return <>
  <PageHero eyebrow="Industrial product specification" title="Dehydrated Potato Flakes (Premium)" text="Consistent, rapid-hydrating potato solids for snack systems, bakery, soups and prepared food manufacturing." image="/images/potato-1.jpg"><div className="button-row"><Link className="button accent" href="/contact">Request sample</Link><a className="button glass" href="#specifications"><Icon name="download" size={18}/> View specifications</a></div></PageHero>
  <section className="section container split product-overview"><div><SectionTitle eyebrow="Technical overview" title="Clean potato character. Reliable process performance." text="Produced from selected potatoes using controlled cooking, mashing and drum drying to retain a natural flavor profile and predictable hydration behavior."/><div className="check-list two-col"><span><Icon name="check"/> Light cream color</span><span><Icon name="check"/> Low reducing sugars</span><span><Icon name="check"/> Smooth mouthfeel</span><span><Icon name="check"/> Batch consistency</span></div></div><ImagePanel src="/images/potato-2.jpg" alt="Premium potato flakes close-up"/></section>
  <section className="section applications"><div className="container"><SectionTitle center eyebrow="Primary applications" title="One ingredient, multiple production formats"/><div className="feature-grid four"><div className="mini-card"><b>Extruded snacks</b><p>Texture and expansion support.</p></div><div className="mini-card"><b>Instant mash</b><p>Rapid hydration and smooth body.</p></div><div className="mini-card"><b>Bakery</b><p>Moisture retention and softness.</p></div><div className="mini-card"><b>Soups & sauces</b><p>Natural thickening and flavor.</p></div></div></div></section>
  <section id="specifications" className="section container spec-layout"><div><SectionTitle eyebrow="Batch parameters" title="Technical specifications" text="Standard commercial targets. Custom parameters are available for contracted volumes."/><div className="spec-table">{specs.map(([key, value]) => <div key={key}><span>{key}</span><strong>{value}</strong></div>)}</div></div><div><SectionTitle eyebrow="Typical values" title="Nutritional value (per 100g)"/><div className="nutrition"><div><strong>357</strong><span>kcal</span></div><div><strong>8.2g</strong><span>Protein</span></div><div><strong>81g</strong><span>Carbohydrate</span></div><div><strong>0.6g</strong><span>Fat</span></div></div><p className="fine-print">Values may vary slightly by crop and production batch.</p></div></section>
  <section className="section container"><SectionTitle center eyebrow="Industrial packaging" title="Configured for your throughput"/><div className="pack-grid"><ImagePanel src="/images/potato-3.jpg" alt="Export packaging for potato flakes"/><ImagePanel src="/images/potato-4.jpg" alt="Bulk bags for industrial ingredients"/><ImagePanel src="/images/potato-5.jpg" alt="Containerized export shipment"/></div><div className="pack-labels"><span><b>Standard export bag</b> 20 kg multi-wall with liner</span><span><b>Jumbo bulk bags</b> Contract volume programs</span><span><b>Container loads</b> Palletized or floor loaded</span></div></section>
  <CTA title="Ready to optimize your production?" text="Request a technical data sheet, commercial sample or landed quote for your destination market."/>
  </>; }
