import Image from "next/image";
import Link from "next/link";
import { Icon } from "@/components/icon";
import { CertificationLogos } from "@/components/brand";
import { OpenMap } from "@/components/open-map";
import { CTA, Eyebrow, FeatureCard, ImagePanel, Metric, SectionTitle } from "@/components/ui";
import { getAllProducts } from "@/lib/db-operations";

async function getProducts() { try { return (await getAllProducts()).slice(0, 4); } catch { return []; } }

export default async function Home() {
  const products = (await getProducts()).map((p) => ({ name: p.name, tag: p.category, image: p.imageUrl || "/images/home-3.jpg", href: `/products/${p.slug}`, note: `${p.description.substring(0, 40)}...` }));
  return <>
    <section className="home-hero"><Image src="/images/home-1.png" alt="Modern food ingredient manufacturing facility" fill priority sizes="100vw" className="cover-image"/><div className="hero-scrim"/><div className="hero-grid-overlay"/><div className="container home-hero-content"><div><Eyebrow>Certified industrial excellence</Eyebrow><h1>Premium dehydrated food ingredients <em>manufactured in India.</em></h1><p>High-performance potato, onion and garlic ingredients made for food manufacturers who cannot compromise on consistency.</p><div className="button-row"><Link className="button accent" href="/contact">Request a quote <Icon name="arrow" size={18}/></Link><Link className="button glass" href="/products">Explore products</Link></div></div><div className="hero-stats glass-panel"><Metric value="25+" label="Years manufacturing"/><Metric value="40+" label="Export countries"/><Metric value="18K" label="MT annual capacity"/></div></div></section>
    <section className="section container split intro-split"><div><Eyebrow>Built for dependable scale</Eyebrow><h2>Pioneering dehydration technology since 1998</h2></div><div><p className="lead">We transform carefully sourced crops into stable, high-functioning ingredients through controlled processing, laboratory verification and export-ready packing.</p><Link className="text-link" href="/manufacturing">See how we manufacture <Icon name="arrow" size={18}/></Link></div></section>
    <section className="section products-section"><div className="container"><SectionTitle eyebrow="Industrial ingredient portfolio" title="Our core products" text="Application-ready ingredients with repeatable color, texture, flavor and hydration performance."/><div className="product-grid">{products.map((p) => <Link className="product-card" href={p.href} key={p.name}><div className="product-image"><Image src={p.image} alt={p.name} fill sizes="25vw" className="cover-image"/><span>{p.tag}</span></div><div><h3>{p.name}</h3><p>{p.note}</p><b>View specification <Icon name="arrow" size={16}/></b></div></Link>)}</div></div></section>
    <section className="section container precision-grid"><ImagePanel src="/images/home-2.png" alt="Technicians monitoring automated food processing lines"/><div className="precision-copy"><SectionTitle eyebrow="Precision manufacturing" title="Control at every critical point" text="Automated lines, low-temperature processing and real-time quality checks protect the characteristics that matter in your finished product."/><div className="check-list"><span><Icon name="check"/> Controlled crop sourcing</span><span><Icon name="check"/> Batch-level traceability</span><span><Icon name="check"/> Custom mesh and moisture targets</span><span><Icon name="check"/> Export-grade barrier packaging</span></div><Link className="button primary" href="/infrastructure">Explore our facility</Link></div></section>
    <section className="section trust-section"><div className="container"><SectionTitle center eyebrow="Assurance by design" title="Trusted globally. Certified locally."/><div className="feature-grid"><FeatureCard icon="shield" title="Food safety verified" text="ISO 22000, HACCP, GMP and FSSAI systems govern every production batch."/><FeatureCard icon="flask" title="In-house analytics" text="Moisture, microbial, sensory and chemical parameters checked before dispatch."/><FeatureCard icon="globe" title="Export documentation" text="Country-ready certificates, labeling and shipment documents for smoother clearance."/></div><CertificationLogos/></div></section>
    <section className="section container export-split"><div><SectionTitle eyebrow="Export footprint" title="From Gujarat to production lines worldwide" text="Our manufacturing and logistics network supports dependable ocean and air freight programs across key international trade corridors."/><Link className="button primary" href="/exports">Explore global reach</Link></div><OpenMap className="map-card"/></section>
    <CTA title="Build a more reliable ingredient supply chain" text="Discuss volume, specifications, samples and private-label requirements with our enterprise team."/>
  </>;
}
