import Link from "next/link";
import { Icon } from "@/components/icon";
import { CertificationLogos } from "@/components/brand";
import { CTA, FeatureCard, ImagePanel, PageHero, SectionTitle } from "@/components/ui";

const tests = [["Moisture content", "AOAC 925.40", "Max 5.0%"], ["Water activity", "AquaLab 4TE", "Below 0.45"], ["Total ash", "IS 1797:1985", "Max 6.5%"], ["Microbial count", "ISO 4833-1", "< 10⁴ CFU/g"], ["Salmonella / 25g", "ISO 6579", "Absent"]];

export default function QualityPage() { return <>
  <PageHero eyebrow="Certified industrial excellence" title="Uncompromising Quality Standards" text="Advanced analysis and disciplined process controls ensure every batch meets global benchmarks for safety, purity and stability." image="/images/quality-1.png"><div className="button-row"><a className="button primary" href="#laboratory">Explore lab capabilities</a><Link className="button glass" href="/contact">Request reports</Link></div></PageHero>
  <section id="laboratory" className="section container facility-grid"><div><SectionTitle eyebrow="Advanced R&D laboratory" title="Scientific verification beyond routine checks" text="Our in-house quality team assesses physical, chemical, microbiological and sensory characteristics that influence shelf life and application performance."/><div className="feature-grid two"><FeatureCard icon="flask" title="Moisture control" text="Precision water activity and thermogravimetric analysis."/><FeatureCard icon="shield" title="Microbial purity" text="Lot-level screening for key pathogens, yeast and mold."/><FeatureCard icon="leaf" title="Phyto-chemical integrity" text="Controlled processing supports aroma and nutrient retention."/><FeatureCard icon="box" title="Packaging validation" text="Seal integrity and coding checked before release."/></div></div><div className="image-stack"><ImagePanel src="/images/quality-2.png" alt="Laboratory analyst testing food ingredients"/><ImagePanel src="/images/quality-3.png" alt="Quality inspection of dehydrated ingredients"/></div></section>
  <section className="section workflow"><div className="container"><SectionTitle center eyebrow="Precision workflow" title="Quality gates from intake to dispatch"/><div className="process-line four-step">{["Raw material screening", "In-process monitoring", "Batch laboratory testing", "Final release & sealing"].map((x, i) => <div key={x}><span>0{i + 1}</span><b>{x}</b></div>)}</div></div></section>
  <section className="section container"><SectionTitle center eyebrow="Globally recognized standards" title="Compliance built into the operating system"/><CertificationLogos/></section>
  <section className="section specs-section"><div className="container"><SectionTitle eyebrow="Typical technical specifications" title="Documented methods. Defined limits." text="Custom quality parameters can be accommodated for contracted industrial programs."/><div className="quality-table"><div className="table-head"><b>Parameter</b><b>Test method</b><b>Industrial standard</b></div>{tests.map((r) => <div key={r[0]}><span>{r[0]}</span><span>{r[1]}</span><strong>{r[2]}</strong></div>)}</div></div></section>
  <CTA title="Treat food safety as a scientific imperative" text="Request our quality dossier, current certifications or a product-specific certificate pack."/>
  </>; }
